v1.0.5
pagseguro/pagbank-for-woocommerce pull request #21
Opened 2023-12-04 16:55 UTC by eliasjnior

* Corrigido bugs durante a instalação.
* Atualizado dependências.
* Corrigido alguns errors do PHPCS.

2023-12-04 17:14 UTC, andrelugomes requested changes

2023-12-04 17:14 UTC, andrelugomes commented on .eslintrc.js
> +        "@eliasjnior/eslint-config-settings/rules/common",
será que o eslint deveria estar apontando pra um repo seu?

Acho que temos que usar algo "mais oficial"

2023-12-04 17:14 UTC, andrelugomes commented on package.json
> +    "@eliasjnior/eslint-config-settings": "^1.0.2",
o mesmo aqui

2023-12-04 17:19 UTC, eliasjnior commented on .eslintrc.js
> +        "@eliasjnior/eslint-config-settings/rules/common",
@andrelugomes são algumas regras do ESLint que deixo compartilhada entre projetos que deixo publicado no NPM https://www.npmjs.com/package/@eliasjnior/eslint-config-settings.

Posso copiar essas regras manualmente para cá, se achar mais interessante.

2023-12-04 17:27 UTC, andrelugomes commented on .eslintrc.js
> +        "@eliasjnior/eslint-config-settings/rules/common",
acho melhor estarem aqui no projeto mano.. na falta de algo Comum do Pags

2023-12-09 13:00 UTC, eliasjnior commented on .eslintrc.js
> +        "@eliasjnior/eslint-config-settings/rules/common",
@andrelugomes estou jogando essa alteração na `v1.0.6`, pois foi a release aprovada pelo time do WordPress recentemente.

2023-12-11 12:27 UTC, andrelugomes approved these changes

2023-12-14 18:13 UTC, merged