v1.0.0
pagseguro/pagbank-for-woocommerce pull request #3
Opened 2023-06-27 14:44 UTC by eliasjnior

2023-06-27 17:02 UTC, andrelugomes requested changes

2023-06-27 17:02 UTC, andrelugomes commented on pagbank-woocommerce.php
> +define( 'PAGBANK_WOOCOMMERCE_VERSION', '0.0.3' );
Uma pergunta por desconhecer a plataforma:

Mas essa versão `0.0.3`  não bate com "version": "0.0.2", no package.json. Nem com a v1.0.0 que é a ideia desse PR

2023-06-27 17:02 UTC, andrelugomes commented on src/core/Presentation/Api.php
> +		$this->log_request_ends( $response_code, $response_body, 'pagbank_oauth' );
@eliasjnior tem um exemplo de como ficam esses LOGs?

Access_token é um informação que devemos evitar logar.

2023-06-27 17:02 UTC, andrelugomes commented on src/core/Presentation/Api.php
> +		$this->log_request_ends( $response_code, $response_body, 'pagbank_oauth' );
o mesmo aqui

2023-06-27 17:02 UTC, andrelugomes commented on src/core/Presentation/Api.php
> +		$this->log_request_begin( $url, $body );
sobre logar dados do pedido. Não devemos logar dados PII, isso pode ser um problema.

tem um exemplo de como isso fica nos logs??

2023-06-27 17:22 UTC, eliasjnior commented on pagbank-woocommerce.php
> +define( 'PAGBANK_WOOCOMMERCE_VERSION', '0.0.3' );
@andrelugomes isso foi um erro mesmo. Essa constante define um argumento `?version=x` na URL da tag dos scripts JS e CSS inseridos pelo plugin. De fato não causa qualquer erro, acaba servindo somente para uma aplicação melhor do cache, caso trabalhe com múltiplas versões. Porém eu encontrei alguns outros detalhes para ajustes que está na branch v1.0.1, então podemos ignorar esse daqui, pois já está corrigido lá.

2023-06-27 17:22 UTC, eliasjnior commented on src/core/Presentation/Api.php
> +		$this->log_request_ends( $response_code, $response_body, 'pagbank_oauth' );
Adicionei na branch v1.0.1 um condicional para somente logar caso haja uma constante definida para desenvolvimento.

2023-07-06 14:31 UTC, andrelugomes approved these changes

2023-07-06 15:26 UTC, merged